[cryptoMaterial]

certPath = "conf"

[network]
peers=["192.168.56.101:20203"]

[account]
keyStoreDir = "account"         # The directory to load/store the account file, default is "account"

accountFileFormat = "p12"       # The storage format of account file (Default is "pem", "p12" as an option)
password="123456"
accountAddress="0x4fa154dd45d9c63c43c43dbb45fffae36ac25deb"

[threadPool]
maxBlockingQueueSize = "102400"             # The max blocking queue size of the thread pool

